### ISSUE TITLE
Streamline adding new algorithms?

### ISSUE THREAD

**Issue by jsoules** [scratchrealm/charactercountcomparison#1]
I wonder if there's a way to make https://github.com/scratchrealm/charactercountcomparison/blob/main/workflow/rules/algorithms/__init__.py pull in everything in the directory rather than needing to be manually updated? I feel like I've seen something like this elsewhere but I don't remember the details...

**Comment by magland** [comment]
I thought about that and there is a way to do it. However, I think in this case the explicit list is better because we need to provide algorithm names (and perhaps other properties) and it's good to see everything all in one place. The other advantage of not automatically parsing the directory structure is that users can easily turn on/off certain algorithms without fussing with more than the one file.

**Comment by jsoules** [comment]
Makes sense.
